<a href="https://colab.research.google.com/github/haneefSaeed/Machine-Learning/blob/master/1_vecotrs_in_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MATHEMATICS** VECTORS

In [2]:
import numpy as np

In [3]:
## defining a vector
v1 = np.array([1,-1, 2])
v2 = np.array([2, 5, 2])

Vector Basic Operations

In [7]:
## addition
print(v1+v2)

## subtraction
print(v1-v2)

## scalar Multiplication
print(3*v1)

[3 4 4]
[-1 -6  0]
[ 3 -3  6]


Numpy vector Operations

In [9]:
## Langth = |v1| = sqrt(x1 + x2 + x3)
print (np.linalg.norm(v1))

2.449489742783178


In [10]:
## Dot product
print (np.dot(v1, v2))

1
