<a href="https://colab.research.google.com/github/haneefSaeed/Machine-Learning/blob/master/Basics_of_Machine_Learning_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**System Specification**

In [ ]:
!cat /proc/cpuinfo


processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
!cat /proc/meminfo

MemTotal:       13290460 kB
MemFree:         9811524 kB
MemAvailable:   12149464 kB
Buffers:          435248 kB
Cached:          2078928 kB
SwapCached:            0 kB
Active:           874636 kB
Inactive:        2350060 kB
Active(anon):       1804 kB
Inactive(anon):   711056 kB
Active(file):     872832 kB
Inactive(file):  1639004 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               244 kB
Writeback:             0 kB
AnonPages:        710536 kB
Mapped:           377328 kB
Shmem:              2332 kB
KReclaimable:     134088 kB
Slab:             173196 kB
SReclaimable:     134088 kB
SUnreclaim:        39108 kB
KernelStack:        5216 kB
PageTables:        11596 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6645228 kB
Committed_AS:    2762052 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11544 kB
VmallocChunk:    

Installing Libraries

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
datafile = pd.read_csv( '/content/sample_data/california_housing_test.csv')

In [ ]:
datafile.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

**Programming Languages (Python , R)**

In [3]:
import numpy as np

In [5]:
from time import process_time

Time Comparesson List vs Numpy List

In [11]:
py_lst = [x for x in range(10000)]

start_time = process_time()

py_list = [x+5 for x in py_lst]

end_time = process_time()

print(end_time - start_time)


0.00030683999999858713


In [15]:
np_arr = np.array([i for i in range(10000)])

start = process_time()

np_arr +=5

end = process_time()

print(end-start)

0.00012380999999983544


In [18]:
a = np.array([(1,2,3), (4,5,6)])
print(a)

print(type(a))
print(a.shape )

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [19]:
# instant conversion

b = np.array([(1,2), (3,4)], dtype='float')
print(b)

[[1. 2.]
 [3. 4.]]


In [30]:
# initial placeholders

z = np.zeros((3,3), dtype='int')
print(z)

o = np.ones((3,4))
print(o)

fulls = np.full((3,2), 34)
print(fulls)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[34 34]
 [34 34]
 [34 34]]


**Identity Matrix**

In [33]:
# x by x matrix

imax = np.eye(4)
print(imax)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
# random Values array

# between 0 and 1
ran = np.random.random((3,4))
print(ran)

# between two integers
rai = np.random.randint(10, 100, (3,4))
print(rai)

[[0.08195304 0.64170326 0.39425409 0.15864923]
 [0.73865056 0.24615478 0.60597379 0.01781397]
 [0.17371243 0.08871256 0.5502083  0.94535309]]
[[35 17 23 10]
 [67 84 20 15]
 [99 30 16 16]]


In [45]:
# array with evenly spaced values

# specify the number of required value (5)
esv = np.linspace(10, 50, 5)
print(esv)

# specify the steps
esvs = np.arange(10,50, 2)
print(esvs)




[10. 20. 30. 40. 50.]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


**NP array specification**

In [48]:
# convert reg list to np

lst = [10,20, 30, 40 , 50, 100]

npArr = np.asarray(lst)
print(type(npArr))

<class 'numpy.ndarray'>


In [56]:
nparr = np.random.randint(1,30, (5,5))
print(nparr)

##shape
print(nparr.shape)

##dimension
print(nparr.ndim)

##size
print(nparr.size)

##datatype
print(nparr.dtype)

[[26  6  6 20  4]
 [11 26  3 15 28]
 [ 1  9 15 12 12]
 [19  6 12 20  8]
 [29  8 15 12 15]]
(5, 5)
2
25
int64


In [60]:
# Mathematical Operations

arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]

## concat
print(arr1 + arr2)

nparr1 = np.random.randint(1,10, (3,3))
nparr2 = np.random.randint(1,10, (3,3))


## operation

print(nparr1+nparr2, np.add(nparr1, nparr2))
print(nparr1-nparr2, np.subtract(nparr1, nparr2))
print(nparr1*nparr2)
print(nparr1/nparr2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 8 11 10]
 [ 9 16 16]
 [ 4 10 15]] [[ 8 11 10]
 [ 9 16 16]
 [ 4 10 15]]
[[-4 -3 -8]
 [ 5  2  2]
 [-2  6 -3]] [[-4 -3 -8]
 [ 5  2  2]
 [-2  6 -3]]
[[12 28  9]
 [14 63 63]
 [ 3 16 54]]
[[0.33333333 0.57142857 0.11111111]
 [3.5        1.28571429 1.28571429]
 [0.33333333 4.         0.66666667]]


In [62]:
arr = np.random.randint(1,20, (2, 4))
print(arr)

trans = np.transpose(arr)
print(trans)

[[ 7  2 10 17]
 [13 16  2 13]]
[[ 7 13]
 [ 2 16]
 [10  2]
 [17 13]]
